export const GET_SEARCH_CITIES_LOADING = "GET_SEARCH_CITIES_LOADING";
export const GET_SEARCH_CITIES_SUCCESS = "GET_SEARCH_CITIES_SUCCESS";
export const GET_SEARCH_CITIES_FAILED = "GET_SEARCH_CITIES_FAILED";

export const GET_CITY_DETAILS_LOADING = "GET_CITY_DETAILS_LOADING";
export const GET_CITY_DETAILS_SUCCESS = "GET_CITY_DETAILS_SUCCESS";
export const GET_CITY_DETAILS_FAILED = "GET_CITY_DETAILS_FAILED";

export const GET_FIVE_DAYS_MORE_LOADING = "GET_FIVE_DAYS_MORE_LOADING";
export const GET_FIVE_DAYS_MORE_SUCCESS = "GET_FIVE_DAYS_MORE_SUCCESS";
export const GET_FIVE_DAYS_MORE_FAILED = "GET_FIVE_DAYS_MORE_FAILED";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";

export const GET_FAVORITES_DATA_LOADING = "GET_FAVORITES_DATA_LOADING";
export const GET_FAVORITES_DATA_SUCCESS = "GET_FAVORITES_DATA_SUCCESS";
export const GET_FAVORITES_DATA_FAILED = "GET_FAVORITES_DATA_FAILED";
